spring:
  application:
    name: Gateway
 
#Data source configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

#Hibernate configuration
  jpa:
    properties:
      hibernate.show_sql: true
            
  messages:
    basename: messages

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#filter for PUT/PATCH/DELETE methods
  mvc:
    hiddenmethod:
      filter:
         enabled: true

    format:
      date: dd/MM/yyyy

#api service
custom:
  api:
    url: ${API_URL}

    